services:
  reverse_proxy:
    image: nginx:stable-alpine
    container_name: dru-reverse-proxy
    ports:
      - '80:80'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./.docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dru

  api:
    container_name: dru-api
    build:
      context: .
      dockerfile: ./.docker/dev/api.dockerfile
    environment:
      - NODE_ENV=development
      - PORT=3001
    ports:
      - '3001:3001'
    platform: linux/amd64
    networks:
      - dru
    volumes:
      - ./apps/api:/usr/src/app/apps/api 
    depends_on:
      - mysql

  mysql:
    image: mysql/mysql-server:8.0
    container_name: dru-mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: dbpass
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: dru
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'dru-mysql:/var/lib/mysql'
    networks:
      - dru

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dru-phpmyadmin
    environment:
      PMA_HOST: dru-mysql
      MYSQL_ROOT_PASSWORD: dbpass
    ports:
      - '8080:80'
    platform: linux/amd64
    depends_on:
      - mysql
    networks:
      - dru

networks:
  dru:
    driver: bridge
volumes:
  dru-mysql:
    driver: local
