name: PR Checks
on:
  pull_request:
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Check base branch
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" != "main" ]]; then
            echo "::error:: ❌ PRs must target 'main' as the base branch."
            exit 1
          fi
  quality:
    runs-on: ubuntu-latest
    needs: [prepare]
    if: needs.prepare.result == 'success'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: 'run api container'
        run: docker compose up -d api
      - run: npm i
      - uses: nrwl/nx-set-shas@v4
      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"
      - name: Code quality
        run: npx nx affected -t lint type-check --base=origin/main --head=refs/remotes/pull/${{ github.event.number }}/merge
